class/urls.py
from django.urls import path
from .views import Studecreate, Studedetail, Studlist, studeDelete, studeupdate


app_name='class'


urlpatterns = [
    path('',Studlist.as_view(),name='students'),
    path('create/',Studecreate.as_view(),name='create-view'),
    path('detail/<int:pk>/',Studedetail.as_view(),name='detail-view'),
    path('update/<int:pk>/', studeupdate.as_view(), name='update-view'),
    path('delete/<int:pk>/',studeDelete.as_view(),name='delete-view')
 
]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('class.urls'))
]

class/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    name=models.CharField(max_length=30,blank=True,null=True)
    adm=models.CharField(max_length=20)
    career=models.CharField(max_length=40,blank=True)
    check=models.BooleanField(default=False)
    time=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'  name{self.name},   adm{self.adm}'
    class Meta:    
        ordering=['name']

class/views.py
from pyexpat import model
from attr import fields
from django.urls import reverse_lazy
from .models import Student
from django.views.generic import ListView
from django.views.generic import CreateView
from django.views.generic import DetailView
from django.views.generic import UpdateView
from django.views.generic import DeleteView
# Create your views here.

#class based views
#Listview

class Studlist(ListView):
    model=Student
    context_object_name='class:students'

#createview
class Studecreate(CreateView):
    model=Student
    fields='__all__'
    success_url=reverse_lazy('class:students')

#detailview


class Studedetail(DetailView):
    model=Student

    fields='__all__'
    success_url=reverse_lazy('class:students'),

class studeupdate(UpdateView):

    model=Student
    fields='__all__'
    success_url=reverse_lazy('class:students')

class studeDelete(DeleteView):

    model=Student
    success_url=reverse_lazy('class:students')

class/templates/class/student_confirm_delete.html
<h1>HELLO WELCOME TO DELETE PAGE</h1>

class/templates/class/student_detail.html
<h2>HELLO YOUR ARE IN DETAIL VIEW</h2>


{% for student in students  %}
<a href="{% url 'class:students' student.id %}" >{{student.name}}</a>
<a href="{% url 'class:update-view' student.id%}" >Update</a>
<a href="{% url 'class:delete-view' student.id %}" >delete</a>
{%  endfor %}

class/templates/class/student_form.html
<h1>HELLO THIS IS create form</h1>


<form  method='POST'  actions=''>
{% csrf_token %}
  {{form.as_p}}
<input type='submit' value='save'>
</form>

class/templates/class/student_list.html
<h1>HELLO AM LEARING DJANGO WITH KIASH</h1>

{% for student in students  %}
<a href="{% url 'class:students' student.id %}" >{{student.name}}</a>
<a href="{% url 'class:update-view' student.id%}" >Update</a>
<a href="{% url 'class:delete-view' student.id %}" >delete</a>
{%  endfor %}